### ISSUE TITLE
[Bug] Weird jumps on grid container with gaps

### ISSUE THREAD

**Issue by felixmosh** [catamphetamine/virtual-scroller#15]
Hi,

I've updated to the latest version (1.6.x), and I've noticed that there are some jumps of the container when the scroller stops.

I'm able to reproduce it on [the demo](https://catamphetamine.gitlab.io/virtual-scroller/).
![ezgif-3-e8c0602e0742](https://user-images.githubusercontent.com/9304194/101913800-28def680-3bcc-11eb-94d1-69842b7677dc.gif)

All you need to do is to add css to the `#messages`
```css
#messages {
    border-top: 2px solid rgb(230, 236, 240);
    display: grid; // <----
    grid-gap: 2em; // <----
}
```

It is not reproduces on `v1.5.x`.
